module.exports = {
	viewports: [
		{ name: 'phone', width: 320, height: 480 },
		{ name: 'laptop', width: 1280, height: 800 }
	],
	scenarios: [{
		label: 'Typography',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#typography'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Blockquotes',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#blockquotes'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Buttons',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#buttons'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Lists',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#lists'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Forms',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#forms'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Tables',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#tables'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Grids',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#grids'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Codes',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#codes'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Utilities',
		url: 'http://milistrap-weblyteam306713.codeanyapp.com:3001',
		hideSelectors: [],
		removeSelectors: ['#__bs_notify__'],
		selectors: ['#utilities'],
		readyEvent: null,
		delay: 5000,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}],
	paths: {
		bitmaps_reference: 'test/reference',
		bitmaps_test: 'node_modules/backstopjs/.tmp/bitmaps_test',
		casper_scripts: 'node_modules/backstopjs/.tmp/casper_scripts',
		html_report: 'node_modules/backstopjs/.tmp/html_report',
		ci_report: 'node_modules/backstopjs/.tmp/ci_report'
	},
	engine: 'phantomjs',
	report: ['browser', 'CLI', 'CI'],
	casperFlags: [],
	debug: true,
	port: 3001
}
